let date =new Date()
console.log(date.getMilliseconds())
console.log(date.getMonth())
console.log(date.getTime())
console.log(Date.now())
let today=new Date(2024,6,1,6,12)
console.log(today.getTime())
console.log(date)
console.log(today)
today.setFullYear(2000)
console.log(today)